version: "1"

services:
  - type: web
    name: yellow-beauty-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "flask db upgrade && gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yellow_beauty_db
          property: connectionString
      - key: SECRET_KEY
        sync: false
    plan: free
    region: oregon
    healthCheckPath: /health

databases:
  - name: yellow_beauty_db
    databaseName: yellow_beauty_db
    user: yellow_beauty_db_user
    plan: basic-256mb
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "18"
    diskSizeGB: 1
